# Receitas


```{r setup, include = FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE, echo = FALSE, results = 'asis')
library(knitr) # para compilar arquivo
library(dplyr) # para manipular os dados
library(glue) # para facilitar a repetição de uma operação
library(stringr) # para manipulação de caracteres
source("functions/diet.R")
source("scripts/01-convert_data.R")

# Objetos necessarios
receitas_id <- read.csv("dados/tabela_01.csv")
ingredientes <- read.csv("dados/tabela_02.csv")

receitas_id <- arrange(receitas_id, Categoria, NOME) %>%
  filter(!is.na(NOME))
categorias <- unique(receitas_id$Categoria)
```


```{r receitas}
for (categoria in categorias) {
  
  cat(glue::glue("\n\n## {tools::toTitleCase(categoria)}\n\n\n\n"))
  
  df <- filter(receitas_id, Categoria == categoria)
  nomes <- unique(df$NOME)  
  
  for (nome in nomes) {
    
    # apenas dados da receita
    df_receita <- filter(receitas_id, NOME == nome)
    df_ingrediente <- filter(ingredientes, NOME == nome)
    
    # tipo de dieta
    veg_check <- ifelse(df_receita$Dieta_Vegetariana == 'Sim', 
                        diet("Dieta_Vegetariana"), "")
    lac_check <- ifelse(df_receita$Dieta_Sem_lactose == 'Sim', 
                        diet("Dieta_Sem_lactose"), "")
    gluten_check <- ifelse(df_receita$Dieta_Sem_glúten == 'Sim', 
                        diet("Dieta_Sem_glúten"), "")
    vegan_check <- ifelse(df_receita$Dieta_Vegana == 'Sim', 
                        diet("Dieta_Vegana"), "")
    
    # Receita info -------------------------------------------------------------
    ## nome
    cat(glue("\n\n### {nome}\n\n"))
    ##quem
    cat(glue("*Receita de {df_receita$Quem_fazia}* {veg_check} {vegan_check} {lac_check}{gluten_check} \n\n"))
    ## memoria
    cat(str_interp('${df_receita$memoria_string}'))
    ## trabalho e tempo de preparo
    cat(glue("\n\n\n\n*É **{tolower(df_receita$Trabalho)}**!
             {df_receita$Tempo_preparo_string}*\n\n\n\n"))
    # rendimento
    cat(glue("\n\n{df_receita$rendimento_string}\n\n\n\n"))
    #cat(str_interp('<br>${veg_check} ${vegan_check} ${lac_check}  ${gluten_check} \n\n'))
    
    # ingredientes -------------------------------------------------------------
    cat("#### Ingredientes\n\n")
    cat(glue(" {df_ingrediente$string} \n\n\n\n"))
    ## preparo -----------------------------------------------------------------
    cat(glue(" \n\n#### Preparo \n\n {df_receita$preparo_string}\n\n\n\n"))
    cat(glue("{df_receita$dicas_string}\n\n\n\n"))
    cat(glue("{df_receita$fonte_string}\n\n\n\n"))
  }
}  

```

:::::: {.cols data-latex=""}

::: {.col data-latex="{0.55\textwidth}"}
TEXTO 1
:::

::: {.col data-latex="{0.05\textwidth}"}
\ 
<!-- an empty Div (with a white space), serving as
a column separator -->
:::

::: {.col data-latex="{0.4\textwidth}"}
TEXTO 2
:::
::::::
